/* Acupoints (腧穴 / Huyệt vị). WHO standard codes.
   view: which figure shows the point. xy: position on the 300×640 figure for the viewer's right side;
   bilateral points are mirrored (x → 300 − x). Midline points have x = 150. */
(function () {
  'use strict';
  var D = window.TCM.data;

  function P(id, ch, view, xy, zh, py, vi, en, loc, act, ind, extra) {
    var o = { id: id, ch: ch, view: view, xy: xy, zh: zh, py: py, vi: vi, en: en, loc: loc, act: act, ind: ind };
    if (extra) for (var k in extra) o[k] = extra[k];
    return o;
  }
  var PREG = { en: 'Contraindicated in pregnancy.', vi: 'Chống chỉ định khi có thai.' };

  D.points = [
    P('LU1', 'LU', 'front', [200, 145], '中府', 'Zhōngfǔ', 'Trung phủ', 'Central Treasury',
      { en: 'On the chest, 6 cun lateral to the midline at the level of the 1st intercostal space, about 1 cun below the infraclavicular fossa.', vi: 'Ở ngực, cách đường giữa 6 thốn, ngang khoang liên sườn 1, dưới hõm dưới đòn khoảng 1 thốn.' },
      { en: 'Front-mu point of the Lung. Descends Lung qi, stops cough and wheezing.', vi: 'Huyệt Mộ của Phế. Giáng phế khí, chỉ khái, bình suyễn.' },
      { en: 'Cough, wheezing, fullness of the chest, shoulder and upper back pain.', vi: 'Ho, hen suyễn, đầy tức ngực, đau vai lưng trên.' },
      { caution: { en: 'Needle obliquely towards the lateral chest. Deep or medial needling risks pneumothorax.', vi: 'Châm xiên ra phía ngoài. Châm sâu hoặc hướng vào trong có nguy cơ tràn khí màng phổi.' } }),
    P('LU7', 'LU', 'front', [240, 309], '列缺', 'Lièquē', 'Liệt khuyết', 'Broken Sequence',
      { en: 'On the radial edge of the forearm, 1.5 cun above the wrist crease, just above the styloid process of the radius.', vi: 'Ở bờ ngoài cẳng tay, trên lằn chỉ cổ tay 1,5 thốn, ngay trên mỏm trâm quay.' },
      { en: 'Luo-connecting point; opening point of the Conception Vessel; command point of the head and neck. Releases the exterior and diffuses Lung qi.', vi: 'Huyệt Lạc; huyệt giao hội với mạch Nhâm; tổng huyệt vùng đầu gáy. Giải biểu, tuyên phế.' },
      { en: 'Common cold, cough, headache, stiff neck, sore throat.', vi: 'Cảm mạo, ho, đau đầu, cứng gáy, đau họng.' }),
    P('LI4', 'LI', 'back', [243, 336], '合谷', 'Hégǔ', 'Hợp cốc', 'Joining Valley',
      { en: 'On the back of the hand, between the 1st and 2nd metacarpal bones, at the midpoint of the radial side of the 2nd metacarpal.', vi: 'Ở mu bàn tay, giữa xương bàn ngón 1 và 2, ngang điểm giữa bờ ngoài xương bàn ngón 2.' },
      { en: 'Source point; command point of the face and mouth. Releases the exterior, stops pain, regulates qi. Paired with LR3 it forms the "Four Gates".', vi: 'Huyệt Nguyên; tổng huyệt vùng mặt, miệng. Giải biểu, chỉ thống, điều khí. Phối với Thái xung gọi là “Tứ quan”.' },
      { en: 'Headache, toothache, facial pain, common cold, fever, pain anywhere in the body.', vi: 'Đau đầu, đau răng, đau mặt, cảm mạo, sốt, đau ở mọi nơi.' },
      { preg: true, caution: PREG }),
    P('LI11', 'LI', 'front', [229, 234], '曲池', 'Qūchí', 'Khúc trì', 'Pool at the Bend',
      { en: 'With the elbow flexed, at the lateral end of the elbow crease, midway between LU5 and the lateral epicondyle.', vi: 'Gấp khuỷu tay, ở đầu ngoài nếp gấp khuỷu, giữa huyệt Xích trạch và mỏm trên lồi cầu ngoài.' },
      { en: 'He-sea point. Clears heat, cools blood, expels wind, resolves damp, benefits the joints.', vi: 'Huyệt Hợp. Thanh nhiệt, lương huyết, khu phong, trừ thấp, lợi khớp.' },
      { en: 'Fever, sore throat, itchy rashes, high blood pressure, elbow pain.', vi: 'Sốt, đau họng, mẩn ngứa, tăng huyết áp, đau khuỷu tay.' }),
    P('LI20', 'LI', 'front', [158, 70], '迎香', 'Yíngxiāng', 'Nghênh hương', 'Welcome Fragrance',
      { en: 'In the nasolabial groove, level with the midpoint of the outer border of the nostril.', vi: 'Ở rãnh mũi má, ngang điểm giữa bờ ngoài cánh mũi.' },
      { en: 'Opens the nasal passages and expels wind.', vi: 'Thông tỵ khiếu, khu phong.' },
      { en: 'Blocked or runny nose, rhinitis, loss of smell, facial paralysis.', vi: 'Ngạt mũi, chảy nước mũi, viêm mũi, mất khứu giác, liệt mặt.' }),
    P('ST25', 'ST', 'front', [168, 255], '天枢', 'Tiānshū', 'Thiên khu', 'Heaven’s Pivot',
      { en: '2 cun lateral to the centre of the navel.', vi: 'Cách rốn 2 thốn sang hai bên.' },
      { en: 'Front-mu point of the Large Intestine. Regulates the intestines, Spleen and Stomach.', vi: 'Huyệt Mộ của Đại trường. Điều hòa trường vị, kiện tỳ.' },
      { en: 'Diarrhoea, constipation, abdominal pain and distension.', vi: 'Tiêu chảy, táo bón, đau và đầy bụng.' },
      { caution: { en: 'Avoid deep needling in pregnancy.', vi: 'Tránh châm sâu khi có thai.' } }),
    P('ST36', 'ST', 'front', [183, 477], '足三里', 'Zúsānlǐ', 'Túc tam lý', 'Leg Three Miles',
      { en: '3 cun below ST35 (the lateral "eye" of the knee), one finger-breadth lateral to the front crest of the tibia.', vi: 'Dưới huyệt Độc tỵ 3 thốn, cách mào chày một khoát ngón tay ra ngoài.' },
      { en: 'He-sea point; command point of the abdomen. Tonifies qi and blood, strengthens the Spleen and Stomach, supports the upright qi.', vi: 'Huyệt Hợp; tổng huyệt vùng bụng. Bổ khí huyết, kiện tỳ hòa vị, phù chính.' },
      { en: 'Stomach pain, vomiting, diarrhoea, fatigue, all deficiency patterns, knee pain. Widely used with moxa for health preservation.', vi: 'Đau dạ dày, nôn, tiêu chảy, mệt mỏi, các chứng hư, đau gối. Hay cứu để dưỡng sinh.' }),
    P('ST40', 'ST', 'front', [185, 520], '丰隆', 'Fēnglóng', 'Phong long', 'Abundant Bulge',
      { en: '8 cun above the lateral malleolus, two finger-breadths lateral to the front crest of the tibia.', vi: 'Trên mắt cá ngoài 8 thốn, cách mào chày hai khoát ngón tay ra ngoài.' },
      { en: 'Luo-connecting point. The key point for transforming phlegm and damp; calms the spirit.', vi: 'Huyệt Lạc. Huyệt chủ yếu để hóa đàm trừ thấp; an thần.' },
      { en: 'Cough with copious phlegm, dizziness, chest oppression, heaviness, obesity.', vi: 'Ho nhiều đờm, chóng mặt, tức ngực, nặng nề, béo phì.' }),
    P('SP6', 'SP', 'front', [162, 562], '三阴交', 'Sānyīnjiāo', 'Tam âm giao', 'Three Yin Intersection',
      { en: '3 cun above the tip of the medial malleolus, just behind the inner border of the tibia.', vi: 'Trên đỉnh mắt cá trong 3 thốn, sát bờ sau trong xương chày.' },
      { en: 'Meeting point of the Spleen, Liver and Kidney channels. Strengthens the Spleen, resolves damp, nourishes blood and yin, regulates menstruation, calms the spirit.', vi: 'Nơi giao hội của ba kinh Tỳ, Can, Thận. Kiện tỳ, trừ thấp, dưỡng huyết, tư âm, điều kinh, an thần.' },
      { en: 'Poor digestion, menstrual disorders, insomnia, urinary problems.', vi: 'Tiêu hóa kém, rối loạn kinh nguyệt, mất ngủ, rối loạn tiểu tiện.' },
      { preg: true, caution: PREG }),
    P('SP9', 'SP', 'front', [163, 465], '阴陵泉', 'Yīnlíngquán', 'Âm lăng tuyền', 'Yin Mound Spring',
      { en: 'In the depression below the medial condyle of the tibia, where the shaft meets the condyle.', vi: 'Ở chỗ lõm dưới lồi cầu trong xương chày.' },
      { en: 'He-sea point. Resolves damp, benefits the lower burner, promotes urination.', vi: 'Huyệt Hợp. Trừ thấp, lợi hạ tiêu, lợi tiểu.' },
      { en: 'Oedema, difficult urination, diarrhoea, knee pain.', vi: 'Phù thũng, tiểu khó, tiêu chảy, đau gối.' }),
    P('SP10', 'SP', 'front', [164, 411], '血海', 'Xuèhǎi', 'Huyết hải', 'Sea of Blood',
      { en: 'With the knee flexed, 2 cun above the upper inner corner of the kneecap, on the bulge of the vastus medialis.', vi: 'Gấp gối, trên góc trong xương bánh chè 2 thốn, trên chỗ nổi của cơ rộng trong.' },
      { en: 'Invigorates and cools blood, regulates menstruation.', vi: 'Hoạt huyết, lương huyết, điều kinh.' },
      { en: 'Irregular or painful periods, eczema, urticaria and other blood-heat skin conditions.', vi: 'Kinh nguyệt không đều, thống kinh, chàm, mề đay và các bệnh da do huyết nhiệt.' },
      { caution: { en: 'Use cautiously in pregnancy because it moves blood strongly.', vi: 'Thận trọng khi có thai vì hoạt huyết mạnh.' } }),
    P('HT7', 'HT', 'front', [230, 320], '神门', 'Shénmén', 'Thần môn', 'Spirit Gate',
      { en: 'On the wrist crease, on the thumb side of the flexor carpi ulnaris tendon (little-finger side of the wrist).', vi: 'Trên lằn chỉ cổ tay, phía ngoài gân cơ gấp cổ tay trụ (phía ngón út).' },
      { en: 'Source point. Calms the spirit and nourishes Heart blood.', vi: 'Huyệt Nguyên. An thần, dưỡng tâm huyết.' },
      { en: 'Insomnia, palpitations, anxiety, poor memory.', vi: 'Mất ngủ, hồi hộp, lo âu, hay quên.' }),
    P('PC6', 'PC', 'front', [234, 306], '内关', 'Nèiguān', 'Nội quan', 'Inner Pass',
      { en: '2 cun above the wrist crease on the palm side, between the tendons of palmaris longus and flexor carpi radialis.', vi: 'Trên lằn chỉ cổ tay 2 thốn ở mặt trong, giữa gân cơ gan tay dài và gân cơ gấp cổ tay quay.' },
      { en: 'Luo-connecting point; opening point of the Yin Linking Vessel. Opens the chest, regulates the Heart, harmonises the Stomach, calms the spirit.', vi: 'Huyệt Lạc; huyệt giao hội với mạch Âm duy. Khoan hung, điều tâm, hòa vị, an thần.' },
      { en: 'Nausea, vomiting, motion sickness, chest tightness, palpitations, anxiety.', vi: 'Buồn nôn, nôn, say tàu xe, tức ngực, hồi hộp, lo âu.' }),
    P('TE5', 'TE', 'back', [234, 306], '外关', 'Wàiguān', 'Ngoại quan', 'Outer Pass',
      { en: '2 cun above the back of the wrist crease, between the radius and ulna, directly opposite PC6.', vi: 'Trên lằn chỉ mu cổ tay 2 thốn, giữa xương quay và xương trụ, đối diện huyệt Nội quan.' },
      { en: 'Luo-connecting point; opening point of the Yang Linking Vessel. Expels wind-heat, releases the exterior, benefits the ears and the side of the head.', vi: 'Huyệt Lạc; huyệt giao hội với mạch Dương duy. Sơ phong thanh nhiệt, giải biểu, lợi tai và vùng thái dương.' },
      { en: 'Fever, colds, tinnitus, one-sided headache, shaoyang disorders, wrist pain.', vi: 'Sốt, cảm mạo, ù tai, đau nửa đầu, bệnh thiếu dương, đau cổ tay.' }),
    P('BL13', 'BL', 'back', [165, 152], '肺俞', 'Fèishū', 'Phế du', 'Lung Shu',
      { en: '1.5 cun lateral to the lower border of the spinous process of T3.', vi: 'Dưới gai đốt sống ngực 3, đo ngang ra 1,5 thốn.' },
      { en: 'Back-shu point of the Lung. Tonifies and diffuses Lung qi.', vi: 'Huyệt Du của Phế. Bổ và tuyên phế khí.' },
      { en: 'Cough, asthma, night sweats, skin disorders.', vi: 'Ho, hen, mồ hôi trộm, bệnh ngoài da.' },
      { caution: { en: 'Needle obliquely towards the spine; deep perpendicular needling risks pneumothorax.', vi: 'Châm xiên hướng vào cột sống; châm thẳng sâu có nguy cơ tràn khí màng phổi.' } }),
    P('BL15', 'BL', 'back', [165, 171], '心俞', 'Xīnshū', 'Tâm du', 'Heart Shu',
      { en: '1.5 cun lateral to the lower border of the spinous process of T5.', vi: 'Dưới gai đốt sống ngực 5, đo ngang ra 1,5 thốn.' },
      { en: 'Back-shu point of the Heart. Calms the spirit and regulates the Heart.', vi: 'Huyệt Du của Tâm. An thần, điều hòa tâm.' },
      { en: 'Palpitations, insomnia, anxiety, chest pain.', vi: 'Hồi hộp, mất ngủ, lo âu, đau ngực.' },
      { caution: { en: 'Oblique needling only.', vi: 'Chỉ châm xiên.' } }),
    P('BL18', 'BL', 'back', [165, 209], '肝俞', 'Gānshū', 'Can du', 'Liver Shu',
      { en: '1.5 cun lateral to the lower border of the spinous process of T9.', vi: 'Dưới gai đốt sống ngực 9, đo ngang ra 1,5 thốn.' },
      { en: 'Back-shu point of the Liver. Spreads Liver qi, nourishes Liver blood, benefits the eyes.', vi: 'Huyệt Du của Can. Sơ can, dưỡng can huyết, sáng mắt.' },
      { en: 'Flank pain, eye problems, jaundice, irritability.', vi: 'Đau mạng sườn, bệnh về mắt, vàng da, dễ cáu giận.' },
      { caution: { en: 'Oblique needling only.', vi: 'Chỉ châm xiên.' } }),
    P('BL20', 'BL', 'back', [165, 228], '脾俞', 'Píshū', 'Tỳ du', 'Spleen Shu',
      { en: '1.5 cun lateral to the lower border of the spinous process of T11.', vi: 'Dưới gai đốt sống ngực 11, đo ngang ra 1,5 thốn.' },
      { en: 'Back-shu point of the Spleen. Tonifies Spleen qi and resolves damp.', vi: 'Huyệt Du của Tỳ. Kiện tỳ ích khí, trừ thấp.' },
      { en: 'Poor appetite, bloating, loose stools, fatigue.', vi: 'Kém ăn, đầy bụng, phân lỏng, mệt mỏi.' },
      { caution: { en: 'Oblique needling only.', vi: 'Chỉ châm xiên.' } }),
    P('BL23', 'BL', 'back', [165, 263], '肾俞', 'Shènshū', 'Thận du', 'Kidney Shu',
      { en: '1.5 cun lateral to the lower border of the spinous process of L2.', vi: 'Dưới gai đốt sống thắt lưng 2, đo ngang ra 1,5 thốn.' },
      { en: 'Back-shu point of the Kidney. Tonifies the Kidney, strengthens the lower back, benefits the ears and bones.', vi: 'Huyệt Du của Thận. Bổ thận, mạnh lưng, lợi tai, mạnh gân xương.' },
      { en: 'Low back pain, tinnitus, urinary disorders, impotence, menstrual problems.', vi: 'Đau lưng, ù tai, rối loạn tiểu tiện, liệt dương, rối loạn kinh nguyệt.' }),
    P('BL40', 'BL', 'back', [177, 446], '委中', 'Wěizhōng', 'Ủy trung', 'Bend Middle',
      { en: 'At the midpoint of the crease behind the knee.', vi: 'Ở điểm giữa nếp lằn khoeo chân.' },
      { en: 'He-sea point; command point of the back. Benefits the lower back, clears heat, cools blood.', vi: 'Huyệt Hợp; tổng huyệt vùng lưng. Lợi lưng gối, thanh nhiệt, lương huyết.' },
      { en: 'Low back pain, knee problems, sciatica, summer-heat.', vi: 'Đau lưng, đau gối, đau thần kinh tọa, cảm nắng.' },
      { caution: { en: 'Avoid the popliteal artery and any varicose veins.', vi: 'Tránh động mạch khoeo và tĩnh mạch giãn.' } }),
    P('BL57', 'BL', 'back', [176, 515], '承山', 'Chéngshān', 'Thừa sơn', 'Supporting Mountain',
      { en: 'On the back of the lower leg, in the depression below the two bellies of the calf muscle, about 8 cun below BL40.', vi: 'Ở mặt sau cẳng chân, chỗ lõm dưới hai bụng cơ dép, dưới Ủy trung khoảng 8 thốn.' },
      { en: 'Relaxes the sinews and treats haemorrhoids.', vi: 'Thư cân, trị trĩ.' },
      { en: 'Calf cramps, haemorrhoids, low back pain.', vi: 'Chuột rút bắp chân, trĩ, đau lưng.' }),
    P('BL60', 'BL', 'back', [181, 586], '昆仑', 'Kūnlún', 'Côn lôn', 'Kunlun Mountains',
      { en: 'In the depression between the tip of the lateral malleolus and the Achilles tendon.', vi: 'Ở chỗ lõm giữa đỉnh mắt cá ngoài và gân gót.' },
      { en: 'Expels wind, relaxes the sinews, clears heat, promotes labour.', vi: 'Khu phong, thư cân, thanh nhiệt, thúc đẻ.' },
      { en: 'Headache at the back of the head, stiff neck, low back pain, ankle pain.', vi: 'Đau đầu vùng chẩm, cứng gáy, đau lưng, đau cổ chân.' },
      { preg: true, caution: PREG }),
    P('KI3', 'KI', 'back', [161, 586], '太溪', 'Tàixī', 'Thái khê', 'Great Stream',
      { en: 'In the depression between the tip of the medial malleolus and the Achilles tendon.', vi: 'Ở chỗ lõm giữa đỉnh mắt cá trong và gân gót.' },
      { en: 'Source point. Tonifies both Kidney yin and Kidney yang, strengthens the lower back.', vi: 'Huyệt Nguyên. Bổ thận âm và thận dương, mạnh lưng.' },
      { en: 'Tinnitus, low back pain, insomnia, night sweats, sore throat from deficiency.', vi: 'Ù tai, đau lưng, mất ngủ, mồ hôi trộm, đau họng do hư.' }),
    P('GB20', 'GB', 'back', [168, 88], '风池', 'Fēngchí', 'Phong trì', 'Wind Pool',
      { en: 'Below the occipital bone, in the hollow between the upper ends of the sternocleidomastoid and trapezius muscles.', vi: 'Dưới xương chẩm, ở chỗ lõm giữa đầu trên cơ ức đòn chũm và cơ thang.' },
      { en: 'Expels wind, clears the head and eyes, calms the Liver.', vi: 'Khu phong, thanh đầu mắt, bình can.' },
      { en: 'Headache, dizziness, common cold, stiff neck, eye problems.', vi: 'Đau đầu, chóng mặt, cảm mạo, cứng gáy, bệnh về mắt.' },
      { caution: { en: 'Needle towards the tip of the nose. Never needle deeply towards the opposite eye (medulla and vertebral artery).', vi: 'Châm hướng về chóp mũi. Không châm sâu hướng về mắt bên đối diện (hành tủy, động mạch đốt sống).' } }),
    P('GB21', 'GB', 'back', [184, 124], '肩井', 'Jiānjǐng', 'Kiên tỉnh', 'Shoulder Well',
      { en: 'At the highest point of the shoulder, midway between GV14 and the tip of the acromion.', vi: 'Ở điểm cao nhất trên vai, giữa huyệt Đại chùy và mỏm cùng vai.' },
      { en: 'Relaxes the sinews, descends qi, promotes lactation and labour.', vi: 'Thư cân, giáng khí, thông sữa, thúc đẻ.' },
      { en: 'Neck and shoulder pain, mastitis, difficult labour.', vi: 'Đau cổ vai, viêm tuyến vú, đẻ khó.' },
      { preg: true, caution: { en: 'Contraindicated in pregnancy. Never needle deeply: the apex of the lung lies below.', vi: 'Chống chỉ định khi có thai. Không châm sâu: bên dưới là đỉnh phổi.' } }),
    P('GB34', 'GB', 'front', [189, 466], '阳陵泉', 'Yánglíngquán', 'Dương lăng tuyền', 'Yang Mound Spring',
      { en: 'In the depression in front of and below the head of the fibula.', vi: 'Ở chỗ lõm phía trước dưới chỏm xương mác.' },
      { en: 'He-sea point; influential point of the sinews. Spreads Liver qi, benefits sinews and joints, clears Liver–Gallbladder damp-heat.', vi: 'Huyệt Hợp; hội huyệt của cân. Sơ can lợi đởm, thư cân lợi khớp, thanh thấp nhiệt can đởm.' },
      { en: 'Flank pain, bitter taste, knee pain, muscle cramps, sciatica.', vi: 'Đau mạng sườn, miệng đắng, đau gối, chuột rút, đau thần kinh tọa.' }),
    P('LR3', 'LR', 'front', [165, 604], '太冲', 'Tàichōng', 'Thái xung', 'Great Surge',
      { en: 'On the top of the foot, in the hollow just in front of where the 1st and 2nd metatarsal bones meet.', vi: 'Ở mu bàn chân, chỗ lõm phía trước khớp nối xương bàn ngón 1 và 2.' },
      { en: 'Source point. Spreads Liver qi, subdues Liver yang, calms the spirit.', vi: 'Huyệt Nguyên. Sơ can lý khí, bình can tiềm dương, an thần.' },
      { en: 'Irritability, headache, dizziness, menstrual problems, high blood pressure.', vi: 'Dễ cáu giận, đau đầu, chóng mặt, rối loạn kinh nguyệt, tăng huyết áp.' }),
    P('GV4', 'GV', 'back', [150, 263], '命门', 'Mìngmén', 'Mệnh môn', 'Gate of Life',
      { en: 'On the midline of the lower back, below the spinous process of L2.', vi: 'Trên đường giữa lưng, dưới gai đốt sống thắt lưng 2.' },
      { en: 'Tonifies Kidney yang and warms the "fire of the gate of vitality"; strengthens the lower back.', vi: 'Bổ thận dương, ôn mệnh môn hỏa, mạnh lưng.' },
      { en: 'Low back pain, cold limbs, impotence, chronic diarrhoea. Often treated with moxa.', vi: 'Đau lưng, chân tay lạnh, liệt dương, tiêu chảy mạn. Hay dùng cứu.' }),
    P('GV14', 'GV', 'back', [150, 118], '大椎', 'Dàzhuī', 'Đại chùy', 'Great Vertebra',
      { en: 'On the midline, below the spinous process of C7 (the prominent bone at the base of the neck).', vi: 'Trên đường giữa, dưới gai đốt sống cổ 7 (đốt nhô cao ở gốc cổ).' },
      { en: 'Meeting point of all yang channels. Releases the exterior, clears heat, supports yang.', vi: 'Nơi hội của các kinh dương. Giải biểu, thanh nhiệt, tráng dương.' },
      { en: 'Fever, colds, stiff neck, alternating chills and fever.', vi: 'Sốt, cảm mạo, cứng gáy, sốt rét (hàn nhiệt vãng lai).' },
      { caution: { en: 'Do not needle deeply (spinal cord).', vi: 'Không châm sâu (tủy sống).' } }),
    P('GV20', 'GV', 'front', [150, 21], '百会', 'Bǎihuì', 'Bách hội', 'Hundred Meetings',
      { en: 'On the top of the head, on the midline where it crosses the line joining the apexes of the ears; 5 cun behind the front hairline.', vi: 'Ở đỉnh đầu, nơi đường giữa gặp đường nối hai đỉnh tai; sau chân tóc trán 5 thốn.' },
      { en: 'Raises yang qi, calms the spirit, benefits the head.', vi: 'Thăng dương, an thần, thanh lợi đầu não.' },
      { en: 'Headache, dizziness, prolapse, insomnia, poor memory.', vi: 'Đau đầu, chóng mặt, sa giáng (sa trực tràng, sa tử cung), mất ngủ, hay quên.' }),
    P('CV4', 'CV', 'front', [150, 285], '关元', 'Guānyuán', 'Quan nguyên', 'Gate of Origin',
      { en: 'On the midline of the lower abdomen, 3 cun below the navel.', vi: 'Trên đường giữa bụng dưới, dưới rốn 3 thốn.' },
      { en: 'Front-mu point of the Small Intestine. Tonifies original qi and the Kidneys, warms yang with moxa, benefits the uterus.', vi: 'Huyệt Mộ của Tiểu trường. Bồi bổ nguyên khí, bổ thận, cứu để ôn dương, lợi bào cung.' },
      { en: 'Exhaustion, frequent urination, menstrual disorders, infertility, chronic diarrhoea.', vi: 'Suy kiệt, tiểu nhiều lần, rối loạn kinh nguyệt, vô sinh, tiêu chảy mạn.' },
      { caution: { en: 'Ask the patient to empty the bladder first. Use caution in pregnancy.', vi: 'Cho bệnh nhân đi tiểu trước khi châm. Thận trọng khi có thai.' } }),
    P('CV6', 'CV', 'front', [150, 270], '气海', 'Qìhǎi', 'Khí hải', 'Sea of Qi',
      { en: 'On the midline, 1.5 cun below the navel.', vi: 'Trên đường giữa bụng, dưới rốn 1,5 thốn.' },
      { en: 'Tonifies qi and yang (especially with moxa) and regulates qi.', vi: 'Bổ khí, ôn dương (nhất là khi cứu), điều khí.' },
      { en: 'Fatigue, abdominal pain, diarrhoea, menstrual problems.', vi: 'Mệt mỏi, đau bụng, tiêu chảy, rối loạn kinh nguyệt.' },
      { caution: { en: 'Use caution in pregnancy.', vi: 'Thận trọng khi có thai.' } }),
    P('CV12', 'CV', 'front', [150, 225], '中脘', 'Zhōngwǎn', 'Trung quản', 'Middle Cavity',
      { en: 'On the midline, 4 cun above the navel (halfway between the navel and the sternocostal angle).', vi: 'Trên đường giữa, trên rốn 4 thốn (giữa rốn và góc ức sườn).' },
      { en: 'Front-mu point of the Stomach; influential point of the fu organs. Harmonises the middle burner, tonifies the Stomach and Spleen, descends rebellious qi.', vi: 'Huyệt Mộ của Vị; hội huyệt của phủ. Hòa trung tiêu, kiện tỳ ích vị, giáng nghịch.' },
      { en: 'Epigastric pain, nausea, vomiting, poor appetite, bloating.', vi: 'Đau thượng vị, buồn nôn, nôn, kém ăn, đầy bụng.' }),
    P('CV17', 'CV', 'front', [150, 180], '膻中', 'Dànzhōng', 'Đản trung (Chiên trung)', 'Chest Centre',
      { en: 'On the midline of the sternum, level with the 4th intercostal space (between the nipples in men).', vi: 'Trên đường giữa xương ức, ngang khoang liên sườn 4 (giữa hai núm vú ở nam).' },
      { en: 'Front-mu point of the Pericardium; influential point of qi. Regulates qi, opens the chest, benefits the breasts.', vi: 'Huyệt Mộ của Tâm bào; hội huyệt của khí. Điều khí, khoan hung, lợi nhũ.' },
      { en: 'Chest tightness, cough, wheezing, insufficient breast milk.', vi: 'Tức ngực, ho, khò khè, ít sữa.' }),
    P('EX-HN3', 'EX', 'front', [150, 50], '印堂', 'Yìntáng', 'Ấn đường', 'Hall of Impression',
      { en: 'At the midpoint between the inner ends of the eyebrows.', vi: 'Ở điểm giữa đầu trong hai cung lông mày.' },
      { en: 'Calms the spirit and opens the nose.', vi: 'An thần, thông mũi.' },
      { en: 'Insomnia, anxiety, frontal headache, rhinitis.', vi: 'Mất ngủ, lo âu, đau đầu vùng trán, viêm mũi.' }),
    P('EX-HN5', 'EX', 'front', [174, 52], '太阳', 'Tàiyáng', 'Thái dương', 'Temple (Supreme Yang)',
      { en: 'At the temple, in the hollow about 1 cun behind the midpoint between the outer end of the eyebrow and the outer corner of the eye.', vi: 'Ở thái dương, chỗ lõm sau điểm giữa đuôi lông mày và đuôi mắt khoảng 1 thốn.' },
      { en: 'Clears heat and benefits the head and eyes.', vi: 'Thanh nhiệt, lợi đầu mắt.' },
      { en: 'One-sided headache, migraine, red painful eyes.', vi: 'Đau nửa đầu, đau đầu migraine, mắt đỏ đau.' })
  ];

  D.pointById = {};
  D.points.forEach(function (p) { D.pointById[p.id] = p; });
})();
